openapi: 3.1.0
info:
  title: Simple API
  version: 1.0.0
paths:
  /:
    summary: simple endpoint
    get:
      operationId: 'getRoot'
  /fart:
    get:
      summary: does a fart
      description: farts real loud
      operationId: opid
