openapi: 3.0.0
info:
  title: Simple API
  version: 1.0.0
paths:
  /:
    get:
      summary: Simple endpoint
      responses:
        '200':
          description: OK
  /fart:
    get:
      summary: does a fart
      description: farts real loud
      operationId: opid
