// Code generated by "stringer -type workflow"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[mainMenu-1]
	_ = x[editSections-2]
	_ = x[endCredits-3]
}

const _workflow_name = "mainMenueditSectionsendCredits"

var _workflow_index = [...]uint8{0, 8, 20, 30}

func (i workflow) String() string {
	i -= 1
	if i < 0 || i >= workflow(len(_workflow_index)-1) {
		return "workflow(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _workflow_name[_workflow_index[i]:_workflow_index[i+1]]
}
