// Code generated by "stringer -type sceneState -trimprefix=scene_"; DO NOT EDIT.

package ui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[scene_mainmenu-0]
	_ = x[scene_root-1]
	_ = x[scene_paths-2]
	_ = x[scene_pathItem-3]
}

const _sceneState_name = "mainmenurootpathspathItem"

var _sceneState_index = [...]uint8{0, 8, 12, 17, 25}

func (i sceneState) String() string {
	if i < 0 || i >= sceneState(len(_sceneState_index)-1) {
		return "sceneState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sceneState_name[_sceneState_index[i]:_sceneState_index[i+1]]
}
